// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next's environment precedence; development is explicitly selected by db:migrate:dev.
const environment = process.env.NODE_ENV || "production";
config({ path: [`.env.${environment}.local`, ".env.local", `.env.${environment}`, ".env"], quiet: true });
const databaseUrl = process.env.DATABASE_URL;
const migrationUrl = databaseUrl ? new URL(databaseUrl) : undefined;
if (migrationUrl) {
  if (
    ["prefer", "require", "verify-ca"].includes(
      migrationUrl.searchParams.get("sslmode") ?? "",
    )
  ) {
    migrationUrl.searchParams.set("sslmode", "verify-full");
  }
  migrationUrl.searchParams.set(
    "schema",
    process.env.DATABASE_SCHEMA || "public",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl?.toString(),
  },
});
